### ISSUE TITLE
Running gradlew sonarqube fails

### ISSUE THREAD

**Issue by Naibeck** [marcinbak/android-sonar-kotlin#1]
Hi, I downloaded your repo since I'm working updating kotlin coverage with jacoco to sonarqube without success till now, and I reach this repo following https://github.com/arturbosch/sonar-kotlin/issues/46. 

Executing the task sonarqube causes the following error:
```
> Task :sonarqube
JUnit report directory not found at C:\Development\android\android-sonar-kotlin\app\sonar-reports


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sonarqube'.
> Provided path 'detekt-config.yml' does not exist!

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 47s
54 actionable tasks: 34 executed, 20 up-to-date
```

You can solve it by adding ../detekt-config.yml and doing so will cause the following error:
```
> Task :sonarqube
JUnit report directory not found at C:\Development\android\android-sonar-kotlin\app\sonar-reports


2 kotlin files were analyzed.
Coverage information was not collected. Perhaps you forget to include debug information into compiled classes?


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sonarqube'.
> File app/src/main/java/de/neofonie/androidsonarkotlin/BusinessLogic.kt can't be indexed twice. Please check that inclusion/exclusion patterns produce disjoint sets for main and test files

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 30s
54 actionable tasks: 34 executed, 20 up-to-date
```
Can you help me setting up your project?

**Comment by marcinbak** [comment]
@Naibeck I've fixed the issue. For some reason it was not looking for detekt configuration file in the root project folder so now I'm stating the absolute path in build.gradle.

The second problem doesn't occur on for me. Maybe it depends on the sonarqube server version/configuration?

**Comment by Simon-Raes** [comment]
Having the same issue here:

```* What went wrong:
Execution failed for task ':sonarqube'.
> File app/src/main/java/de/neofonie/androidsonarkotlin/MainActivity.kt can't be indexed twice. Please check that inclusion/exclusion patterns produce disjoint sets for main and test files
```
Running Sonarqube Version 7.0 (build 36138) locally.

**Comment by Naibeck** [comment]
Same here using Sonarqube v 7.0

**Comment by marcinbak** [comment]
@Naibeck @Simon-Raes I've been working with SonarQube 6.4, 6.5 as newer versions have some significant changes and some plugins are not compatible with them.

**Comment by DaRolla** [comment]
Hi there,

I am using SonarQube 7.2.1 and I get this "indexed twice" problem as well.

Here I found my solution: https://stackoverflow.com/questions/45638477/sonar-fails-with-cant-be-indexed-twice-please-check-that-inclusion-exclusion-p?rq=1

So, in build.gradle I commented out the "sonar.sources" and the "sonar.tests", it compiles, but I do NOT get any coverage :-(

**Comment by rokjsn** [comment]
Same here as @DaRolla

**Comment by saptan** [comment]
Same here as @DaRolla, but i am using SonarQube 6.7.5 (build 38563). If i set this properties sonarcube gradle compile success
```
    property "sonar.sources", "app/src/main/java"
    property "sonar.tests", ["src/test/java", "src/test/kotlin"]

    property "sonar.exclusions", "app/src/main/java/**"
    property "sonar.test.inclusions", "app/src/test/java/**"
```

Jacoco test reports show code coverage, but sonar nothing

**Comment by marcinbak** [comment]
I'm going to come back to the topic this week, trying to use Sonarqube 6.7 that has Kotlin support. Once I manage working setup, will push the changes here.

**Comment by saptan** [comment]
Hi @marcinbak ! Do I have any chance to see a solution to this problem. Unfortunately, I was still unable to implement code analysis on Kotlin.

**Comment by marcinbak** [comment]
@saptan sorry, it's been so busy year that I had no free time whatsoever. As mentioned above we want to migrate to Sonarqube 6.7 at work, so once this is done I'll definitely update this repo.

**Comment by marcinbak** [comment]
@saptan managed to use sonarqube 6.7 and configure the project properly. Please try again according to steps in README.md
